### ISSUE TITLE
Welcome to Mozilla Study Groups!

### ISSUE THREAD

**Issue by auremoser** [MasseyStudyGroup/masseystudygroup.github.io#2]
Hello @MasseyStudyGroup !

Thanks for your interest in the [Mozilla Science Lab](https://science.mozilla.org/), it's great to hear you're building a [Study Group](https://github.com/mozillascience/studygroup).

My name is [Aurelia](https://mozillians.org/en-US/u/aurelia/) and I work at the Mozilla Science Lab, a group building projects/programs globally to support open research and citizen science, including the Study Groups project. Just wanted to introduce myself as a resource, and answer any questions you might have.

Feel free to:
* review our new [Study Group Orientation Guide](https://mozillascience.github.io/study-group-orientation/) developed by @zee-moz
* build out [a site for your Study Group](https://www.youtube.com/watch?v=vVXfx6NmbJE) and cull from our [library of lessons](https://github.com/mozillascience/studyGroupLessons) for early sessions
* join our monthly study group call (first Fridays, 11AM EST), [subscribe to our mailing list to be notified of those calls](https://mail.mozilla.org/listinfo/msl-study-groups)
* add your first Study Group event to our [Events Form](https://docs.google.com/forms/d/e/1FAIpQLSc_YVyXIgxHleSLawwIzlnuM28oJ7phDLHT-SpUJVqVmE93qA/viewform?c=0&w=1) so we can promote it in our Mozilla Network on the [Study Group Events](https://mozillascience.github.io/studyGroupEvents/) site
* follow our #mozstudy hashtag on twitter, or [our list](https://twitter.com/MozillaScience/lists/mozstudy), ping [@auremoser](https://twitter.com/auremoser) to be added

**Join us on our next [Study Group Learning call](https://public.etherpad-mozilla.org/p/mozilla-studygroup-leads-jun-2017), Friday June 2nd, 11am EST**.

Email me at [aurelia@mozillafoundation.org](mailto:aurelia@mozillafoundation.org) with questions, or contact/social media information to join our twitter community and Study Group email listserv. Would love to learn about your lessons, challenges, topic of interest, and events. 

Oh also! Let me know what city you're based in, and I'll add you to our [study group map](https://science.mozilla.org/programs/studygroups).

Thanks for reading!

Aurelia
Mozilla Science Lab
[@MozillaScience](https://twitter.com/mozillascience)

**Comment by phcerdan** [comment]
Thanks a lot Aurelia, we will definitively have all that information into account to prepare our next meeting! 
We are based on Massey University, Palmerston North, New Zealand.

**Comment by auremoser** [comment]
Hurray! I added you to our map/site!

![screen shot 2017-05-10 at 4 42 27 pm](https://cloud.githubusercontent.com/assets/1559703/25904693/41a9b97e-35a0-11e7-8bfd-2b31d3b77bbd.png)


Thank you!
